// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID        int32
	UserID    int32
	Title     string
	Content   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID        int32
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
}
